services:
  httpd_service:
    image: 'httpd'
    networks:
      - 'Network-A'
    ports:
      - '80:80'
    volumes:
      - '/mnt/Slave:/usr/local/apache2/htdocs'
    command: ["sh", "-cd", "chmod -R 777 /usr/local/apache2/htdocs" ]
  
  tomcat_service:
    image: 'tomcat:9'
    networks:
      - 'Network-B'
    ports:
      - '8080:8080'
    volumes:
      - '/mnt/Slave:/usr/local/tomcat/webapps/' 

networks:
  Network-A:
  Network-B:
