services:
  httpd_service:
    image: 'httpd'
    networks:
      - 'Network-A'
    ports:
      - '80:80'
    volumes:
      - '/mnt/Slave:/usr/local/apache2/htdocs'
  
  tomcat_service:
    image: 'tomcat:9'
    networks:
      - 'Network-B'
    ports:
      - '8080:8080'
    volumes:
      - '/mnt/tomcat:/usr/local/tomcat/webapps/'
    command: 'sudo wget https://ap-south-1.console.aws.amazon.com/s3/object/vel-bucket-manish15022026?region=ap-south-1&prefix=2026Q1/car-showroom-1.0.war' 

networks:
  Network-A:
  Network-B:
